/*
ふくすうのページに渡って共有されるUI
*/

import type { Metadata } from "next";
import { Inter,Noto_Sans_JP } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });    //フォントの指定
const notoSansJP = Noto_Sans_JP({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "ClockUP-α", //タブのタイトル
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" >


      

      <body className={notoSansJP.className}>
        <h1 className="bg-emerald-400 h-12">header</h1>
        {children}
        <h1 className="bg-sky-400 h-6">footer</h1>
      </body>
    </html>
  );
}
